// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DocumentListController from "./document_list_controller"
application.register("document-list", DocumentListController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PdfEditorController from "./pdf_editor_controller"
application.register("pdf-editor", PdfEditorController)

import PdfPreviewController from "./pdf_preview_controller"
application.register("pdf-preview", PdfPreviewController)

import ThemeToggleController from "./theme_toggle_controller"
application.register("theme-toggle", ThemeToggleController)